<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Outstanding_SO1 extends Model
{
    protected $table = 'outstanding_so_t_data1';
    protected $primaryKey = 'id';
    protected $fillable = [
        'mandt',
        'kunnr',
        'name1',
        'auart',
        'auart2',
        'types',
        'vbeln',
        'posnr',
        'netpr',
        'netwr',
        'totpr',
        'totpr2',
        'waerk',
        'edatu',
        'werks',
        'bstnk',
        'kwmeng',
        'bmeng',
        'vrkme',
        'meins',
        'matnr',
        'maktx',
        'kalab',
        'kalab2',
        'qty_delivery',
        'qty_gi',
        'qty_balance',
        'qty_balance2',
        'mengx1',
        'mengx2',
        'menge',
        'assy',
        'paint',
        'packg',
        'qtys',
        'ebdin',
        'machp',
        'ebdip',
        'type1',
        'type2',
        'type',
        'dayx',
        'machi',
        'cutt',
        'assym',
        'assymt',
        'primer',
        'paintm',
        'paintmt',
        'packgm',
        'prsm',
        'prsm2',
        'qprom',
        'qodrm',
        'qproa',
        'qodra',
        'prsa',
        'qproi',
        'qodri',
        'prsi',
        'qprop',
        'qpdrp',
        'prsp',
        'qproc',
        'qodrc',
        'prsc',
        'qproam',
        'qodram',
        'prsam',
        'qproir',
        'qodrir',
        'prsir',
        'qproimt',
        'qodrimt',
        'prsimt',
        'name4',
        'kmtl',
        'erdat',
    ];
}
